version: '3.8'

services:
  # Serviço do frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
    container_name: valops_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - reverse-proxy
    environment:
      - VITE_APP_TITLE=ValOps
      - VITE_APP_ENV=production
      - VITE_APP_VERSION=1.0.0
      - VITE_DEBUG=false

  # Proxy reverso para permitir a comunicação entre front e back
  reverse-proxy:
    image: nginx:alpine
    container_name: valops_proxy
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - backend-network

networks:
  default:
    driver: bridge
  backend-network:
    external: true
    name: valops-backend_default