version: '3.4'

services:
  # Serviço do frontend
  frontend:
    image: registry.cloud1.intranet.bb.com.br/dicoi/uor283930/valops-front
    networks:
      - edge
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.dicoi-valops-back.rule=Host(`app.dicoi.intranet.bb.com.br`) && PathPrefix(`/valops-front`)'
        - 'traefik.http.routers.dicoi-valops-back.entrypoints=websecure'
        - 'traefik.http.routers.dicoi-valops-back.tls=true'
        - 'traefik.http.routers.dicoi-valops-back.middlewares=c1-traefik2-intranet, c1-traefik2-gzip'
        - 'traefik.http.services.dicoi-valops-back.loadbalancer.server.port=5010'
      placement:
        constraints:
          - node.labels.deploy == true
        preferences:
          - spread: node.labels.deploy
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_BASE_URL:-http://10.2.98.165:8000}
    container_name: valops_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - reverse-proxy
    environment:
      - VITE_APP_TITLE=ValOps
      - VITE_APP_ENV=production
      - VITE_APP_VERSION=1.0.0
      - VITE_DEBUG=false

  # Proxy reverso para permitir a comunicação entre front e back
  reverse-proxy:
    image: nginx:alpine
    container_name: valops_proxy
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - frontend-network

networks:
  default:
    driver: bridge
  backend-network:
    external: true
    name: valops-frontend_default